name: Project CICD

on:
  push:
    branches: [ "main" ]  # Workflow sẽ chạy khi có commit vào nhánh main
  pull_request:
    branches: [ "main" ]  # Workflow cũng sẽ chạy khi có PR vào nhánh main

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
    # Bước 1: Checkout mã nguồn từ GitHub repository
    - uses: actions/checkout@v4

    # Bước 2: Cài đặt JDK 21 từ Temurin
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'  # Cài đặt Java version 21
        distribution: 'temurin'  # Chọn Temurin làm distribution
        cache: maven  # Cache dependencies của Maven

    # Bước 3: Build ứng dụng bằng Maven
    - name: Build with Maven
      working-directory: ./EchoCuckoo-Backend  # Đảm bảo rằng đây là thư mục chứa pom.xml của bạn
      run: mvn clean install -DskipTests  # Lệnh Maven để build ứng dụng mà bỏ qua bước test (nếu cần)

    # Bước 4: Đăng nhập vào Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Lấy username từ GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Lấy password từ GitHub Secrets

    # Bước 5: Build và push Docker image
    - name: Build & push Docker image
      uses: docker/build-push-action@v3  # Sử dụng Docker Build and Push Action (v3)
      with:
        context: ./EchoCuckoo-Backend  # Đảm bảo chỉ định đúng thư mục chứa Dockerfile
        file: ./EchoCuckoo-Backend/Dockerfile  # Đảm bảo chỉ định đúng đường dẫn đến Dockerfile
        push: true  # Push image lên Docker Hub
        tags: boboibo/springboot-images-new:v1, boboibo/springboot-images-new:latest  # Tag Docker image
